name: Auto Close PR
description: Close PRs whose body text don't match with given patterns.
author: imba-tjd
branding:
  icon: git-pull-request
  color: red

inputs:
  pattern:
    description: The pattern that to be greped.
    required: true
  token:
    default: ${{ github.token }}
    required: false
  message:
    default: This PR was automatically closed because it did not follow the PR template.
    required: false

runs:
  using: composite
  steps:
    - run: |
        cat > body.txt << BODY_END
        ${{ github.event.pull_request.body }}
        BODY_END

        if [ $(grep '${{ inputs.pattern }}' body.txt) ]; then exit; fi;

        set -e;
        echo ${{ inputs.token }} | gh auth login --with-token;
        gh pr close ${{ github.event.pull_request.number }} -R ${{ github.repository }};
        if [ '${{ inputs.message }}' ]; then
          gh pr review ${{ github.event.pull_request.number }} -R ${{ github.repository }} -c -b '${{ inputs.message }}';
        fi;
      shell: bash
